// Code generated by mkskill. DO NOT EDIT.

package main

import (
	_ "embed"

	"github.com/pablo-botella/mkskill"
)

//go:embed mkskill_docs/README.md
var mkskillReadme string

//go:embed mkskill_docs/AGENTS.md
var mkskillAgents string

//go:embed mkskill_docs/SKILL.md
var mkskillSkill string

// MkskillSpec carries the composed documentation views, ready for the
// generate commands (mkskill.CheckParams and friends).
var MkskillSpec = mkskill.Spec{
	Name:        "miniskin",
	Description: "Use when working with miniskin templates, mockup files, *.miniskin.xml configuration, or Go projects that use github.com/pablo-botella/miniskin",
	Readme:      mkskillReadme,
	Agents:      mkskillAgents,
	Skill:       mkskillSkill,
}
